### ISSUE TITLE
Why aren't you telling the masses about this instrument?

### ISSUE THREAD

**Issue by hirrolot** [sepehrdaddev/Xerxes#31]
I think it will be good if you will tell about this instrument on [Reddit](https://www.reddit.com/), [ProductHunt](https://www.producthunt.com/) and other resources. It might be very useful for some people)

**Comment by sepehrdaddev** [comment]
@Gymmasssorla Thank you for your awesome idea, I will share it on twitter.
and I you can share it or tell your friends please do it

**Comment by hirrolot** [comment]
I think twitter is not good enough for such things. I published my repository on Reddit yesterday and have 50+ stars just for doing it.

**Comment by sepehrdaddev** [comment]
@Gymmasssorla on what subreddit did you publish it ?

**Comment by hirrolot** [comment]
I published on [Rust](https://www.reddit.com/r/rust/), but since your project isn't on Rust, you can publish it on [Hacking](https://www.reddit.com/r/hacking/) or on [C programming](https://www.reddit.com/r/C_Programming/)

**Comment by sepehrdaddev** [comment]
@Gymmasssorla awesome, thanks
